services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - n8n_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:1.85.4
    ports:
      - "5678:5678"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      N8N_COMMUNITY_PACKAGES_ENABLED: "true"
      N8N_CUSTOM_EXTENSIONS: /extensions
      N8N_SECURE_COOKIE: "false"
      N8N_DISABLE_PRODUCTION_MAIN_PROCESS: "true"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./extensions:/extensions
    command: ["n8n", "start"]

volumes:
  n8n_pgdata:
  n8n_data: